# PHP server
version: '3'

services:
  api:
    image: 'php:8.1-apache'
    container_name: "parkstras_api"
    ports:
      - '80:80'
    volumes:
      - './api:/var/www/html'
    restart: unless-stopped
