name: Production deployment

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Mise en production de 'ParkStras API'."
            }

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "app/"
          REMOTE_HOST: 37.59.180.192
          REMOTE_USER: u299692851
          REMOTE_PORT: 65002
          EXCLUDE: "db"
          TARGET: /home/u299692851/domains/princelle.org/public_html/parkstras

      - name: Notify on success
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application 'ParkStras API' a bien été déployée."
            }
      - name: Notify on failure
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Erreur lors du déploiement de 'ParkStras API'."
            }
