name: Production deployment

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
          
      - name: Notify
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Mise en production de 'ParkStras API'."
            }

      - name: Deploy to Infomaniak
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "app/"
          REMOTE_HOST: 464i8.ftp.infomaniak.com
          REMOTE_USER: 464i8_ci
          EXCLUDE: "db"
          TARGET: /home/clients/04cd6fa9bfb5342793851e99c0041e14/sites/services/parkstras

      - name: Notify on success
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "L'application 'ParkStras API' a bien été déployée sur l'infrastructure Infomaniak."
            }
      - name: Notify on failure
        if: ${{ failure() }}
        uses: jasongitmail/fast-webhook@v1.1.4
        with:
          url: https://api.pushover.net/1/messages.json
          json: |
            {
              "token": "${{ secrets.PUSHOVER_TOKEN }}",
              "user": "${{ secrets.PUSHOVER_USER }}",
              "message": "Erreur lors du déploiement de 'ParkStras API' sur l'infrastructure Infomaniak."
            }